### ISSUE TITLE
Stopped working Mar-2020 when .itemPriceDrop class was removed

### ISSUE THREAD

**Issue by simonozzy** [mrbusche/amazon-price-drops#4]
Hi Matt, great script which I've used almost daily for over a year and found many a deal!

As of 18-Mar-2020 it stopped working (UK site, I assume .com as well?) Reason being the span now looks like this, with no .itemPriceDrop class :
<span class="a-size-small a-color-tertiary">Price dropped by £0.01</span>

// .. -> so could var priceDrop become something like this, with a valid search function instead of "includes" (which I guessed) ?
var priceDrop = listItems[i].querySelectorAll('.a-color-tertiary').textContent.includes('Price dropped');

I tried, but my .js isn't quite good enough.

Also, for extra points, could the script only show drops greater than say 30%?

Thanks!

**Comment by simonozzy** [comment]
Ah, I've just seen your fix for this and right after it broke - I should have checked before posting! 

.innerText.startsWith('Price dropped');   nice.

Just the feature request then: could the script only show drops greater than say 30%? 
It seems to assume cater for $ amounts but for .co.uk at least, it always shows % drop if it's over around 2%

**Comment by simonozzy** [comment]
me again .. with news that .itemPriceDrop is back! .co.uk html is below:

```
<div class="a-row itemPriceDrop">
            <span id="itemPriceDrop_I1TM5100NQRJDO" class="a-text-bold">
                Price dropped 40%
            </span>       
</div>

```
I wonder if Amazon is trying to keep us guessing here ..

**Comment by mrbusche** [comment]
lol, yes, there are quite a few versions they have in the wild, I'll see what I can figure out with the price drop %

**Comment by mrbusche** [comment]
parsing fixed and price drop % added https://github.com/mrbusche/amazonPriceDrops/pull/5
Update `priceDropMin` to be the minimum % you want to see for price drops

**Comment by simonozzy** [comment]
Installed and working perfectly, with the new priceDropMin set to 10%.  
Big thanks for this, Matt!

**Comment by chicagobeck** [comment]
Ditto.  Thanks for all you do with this, Matt!  I rely on it regularly.
    On Tuesday, July 7, 2020, 09:28:19 AM CDT, AltruisTech <notifications@github.com> wrote:  
 
 


Installed and working perfectly, with the new priceDropMin set to 10%.
Big thanks for this, Matt!
